FROM node:22-alpine AS build
WORKDIR /app
COPY package*.json ./
RUN npm ci --legacy-peer-deps
COPY . .

ARG REMOTE_SGP_URL=https://teraprox-sgp.web.app
ARG REMOTE_SGM_URL=https://teraprox-sgm.web.app
ENV REMOTE_SGP_URL=${REMOTE_SGP_URL}
ENV REMOTE_SGM_URL=${REMOTE_SGM_URL}

RUN npm run build

FROM node:22-alpine
RUN npm install -g serve
WORKDIR /app
COPY --from=build /app/dist ./dist
EXPOSE 3001
CMD ["serve", "-s", "dist", "-l", "3001"]
