import { endPointCaderno, endPointManutencao, endPointNotification, endPointUser, paths } from "./constantes";

export const routesConfig = [
    {
        service: "notification",
        routes: [
            { configuration: { context: "notification", endPoint: endPointNotification } },
        ],
    },
    {
        service: "processo",
        routes: [
            { configuration: { context: "processo", path: paths.processos, endPoint: endPointCaderno } },
            { configuration: { context: "parametro", path: paths.parametros, endPoint: endPointCaderno } },
            { configuration: { context: "fluxoDeProcesso", path: paths.fluxos, endPoint: endPointCaderno } },
            { configuration: { context: "operacao", path: paths.operacoes, endPoint: endPointCaderno } },
            { configuration: { context: "planoDeControle", path: paths.planosDeControle, endPoint: endPointCaderno } },
            { configuration: { context: "linhaDePlanoDeControle", path: paths.linhaDePlanoDeControleForm, endPoint: endPointCaderno } },
            { configuration: { context: "cadernoDeVerificacao", path: paths.cadernos, endPoint: endPointCaderno } },
            { configuration: { context: "folhaDeVerificacao", path: paths.cadernoDeVerificacao, endPoint: endPointCaderno } },
            { configuration: { context: "cadernos", path: paths.cadernos, endPoint: endPointCaderno } },
            { configuration: { context: "registroDeCampo", path: paths.reporte, endPoint: endPointCaderno } },
            { configuration: { context: "campoDeVerificacao", path: paths.cadernos, endPoint: endPointCaderno } },
            { configuration: { context: "acao", path: paths.acoes, endPoint: endPointCaderno } },
            { configuration: { context: "material", path: paths.materiais, endPoint: endPointCaderno } },
            { configuration: { context: "unidadeMaterial", path: paths.unidades, endPoint: endPointCaderno } },
            { configuration: { context: "ordemDeCorrecao", path: paths.ordensDeCorrecao, endPoint: endPointCaderno } },
            { configuration: { context: "regraDeCorrecao", path: paths.regraDeCorrecaoForm, endPoint: endPointCaderno } },
            { configuration: { context: "limiteDeControle", path: paths.planosDeControle, endPoint: endPointCaderno } },
            { configuration: { context: "especificacao", path: paths.planosDeControle, endPoint: endPointCaderno } },
            { configuration: { context: "controle", path: paths.planosDeControle, endPoint: endPointCaderno } },
            { configuration: { context: "formulario", path: paths.formularios, endPoint: endPointCaderno } },
            { configuration: { context: "regraDeValidacao", path: paths.formularios, endPoint: endPointCaderno } },
        ],
    },
    {
        service: "manutencao",
        routes: [
            { configuration: { context: "ordemDeServico", path: paths.ordensDeServico, endPoint: endPointManutencao } },
            { configuration: { context: "ordemDeServico", path: paths.osChart, endPoint: endPointManutencao } },
            { configuration: { context: "ordemDeServico", path: paths.planejamentoDeOs, endPoint: endPointManutencao } },
            { configuration: { context: "ordemDeServico", path: paths.modelosDeOrdemDeServico, endPoint: endPointManutencao } },
            { configuration: { context: "ordemDeServico", path: paths.visaoGeralDeMateriaPrima, endPoint: endPointManutencao } },
            { configuration: { context: "visaoGeral", path: paths.visaoGeralManutencao } },
            // Hexagonal remote (SGM-SS): context já está na base URL — paths são relativos ao contexto
            { configuration: { context: "solicitacaoDeServico", path: paths.solicitacoesDeServico, endPoint: `${endPointManutencao}solicitacaoDeServico` } },
            { configuration: { context: "solicitacaoDeServico", path: paths.solicitacaoDeServicoForm, endPoint: `${endPointManutencao}solicitacaoDeServico` } },
            { configuration: { context: "solicitacaoDeServico", path: paths.aprovaStatus, endPoint: `${endPointManutencao}solicitacaoDeServico` } },
            { configuration: { context: "ordemDeManutencao", path: paths.ordensDeManutencao, endPoint: endPointManutencao } },
            { configuration: { context: "ordemDeManutencao", path: paths.ordemDeManutencaoForm, endPoint: endPointManutencao } },
            { configuration: { context: "ordemDeManutencao", path: paths.executarOrdemDeManutencao, endPoint: endPointManutencao } },
            { configuration: { context: "agregador", path: paths.agregadores, endPoint: endPointManutencao } },
            { configuration: { context: "arvoreEstrutural", path: paths.arvoreEstruturalForm, endPoint: endPointManutencao } },
            { configuration: { context: "recurso", path: paths.recursos, endPoint: endPointManutencao } },
            { configuration: { context: "recurso", path: paths.recursoForm, endPoint: endPointManutencao } },
            { configuration: { context: "acao", path: paths.acoes, endPoint: endPointManutencao } },
            { configuration: { context: "tarefa", path: paths.tarefas, endPoint: endPointManutencao } },
            { configuration: { context: "tarefa", path: paths.tarefaForm, endPoint: endPointManutencao } },
            { configuration: { context: "mantenedor", path: paths.mantenedores, endPoint: endPointManutencao } },
            { configuration: { context: "mantenedor", path: paths.mantenedorForm, endPoint: endPointManutencao } },
            { configuration: { context: "tipoDeOrdem", path: paths.tiposDeOrdem, endPoint: endPointManutencao } },
            { configuration: { context: "tipoDeOrdem", path: paths.tipoDeOrdemForm, endPoint: endPointManutencao } },
            { configuration: { context: "unidade", path: paths.unidades, endPoint: endPointManutencao } },
            { configuration: { context: "unidade", path: paths.unidadeForm, endPoint: endPointManutencao } },
            { configuration: { context: "materiais", path: paths.materiais, endPoint: endPointManutencao } },
            { configuration: { context: "material", path: paths.materialForm, endPoint: endPointManutencao } },
            { configuration: { context: "inspecao", path: paths.inspecoesDashboard } },
            { configuration: { context: "monitoramentoRecursos", path: paths.monitoramentoRecursos } },
            { configuration: { context: "componente", path: paths.componenteForm, endPoint: endPointManutencao } },
            { configuration: { context: "branchLevel", path: paths.branchLevelForm, endPoint: endPointManutencao } },
            { configuration: { context: "classeDeComponente", path: paths.classeDeComponenteForm, endPoint: endPointManutencao } },
            { configuration: { context: "classeDeRecurso", path: paths.classeDeRecursoForm, endPoint: endPointManutencao } },
            { configuration: { context: "modoDeFalha", path: paths.modoDeFalhaForm, endPoint: endPointManutencao } },
            { configuration: { context: "registroDeTarefa", path: paths.registroDeTarefaForm, endPoint: endPointManutencao } },
            { configuration: { context: "dimensao", path: paths.dimensaoForm, endPoint: endPointManutencao } },
        ],
    },
    {
        service: "user",
        routes: [
            { configuration: { context: "user", path: paths.usuarios, endPoint: endPointUser } },
            { configuration: { context: "setor", path: paths.setores, endPoint: endPointUser } },
            { configuration: { context: "company", path: paths.empresas, endPoint: endPointUser } },
            { configuration: { context: "permissao", path: paths.permissoes, endPoint: endPointUser } },
        ],
    },
]
